# Generated by Django 3.1.1 on 2020-10-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
