# Generated by Django 3.1.1 on 2020-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='county',
            field=models.CharField(max_length=100),
        ),
    ]
